# Bible Explore

Exploring [Kaggle Bible Corpus](https://www.kaggle.com/oswinrh/bible) for similarity between passages.

Some extra information at [OpenBible](http://www.openbible.info/) and [Bible Databases](https://github.com/scrollmapper/bible_databases)

The current work is started in English and might be extended to other languages later on

In [91]:
import scipy as sp
import numpy as np
import pandas as pd
import csv
import os
import sys
import re
from queue import Queue
from pathlib import Path
import seaborn as sns
import bokeh
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
import networkx as nx
from pyvis.network import Network
import pickle

%matplotlib inline

In [2]:
# https://stackoverflow.com/questions/18424228/cosine-similarity-between-2-number-lists
# from scipy.spatial import distance
# scipy.spatial.distance.cosine

# or with numpy:
# from numpy import dot
# from numpy.linalg import norm

# cos_sim = dot(a, b)/(norm(a)*norm(b))

In [3]:
# this is for Tensorflow to use the good GPU instead of the first it sees
# os.environ["CUDA_VISIBLE_DEVICES"]="1"
# and this is to set tf to use the GPU

In [4]:
print(tf.__version__)
print(tf.config.list_physical_devices())


2.3.2
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'), PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'), PhysicalDevice(name='/physical_device:XLA_GPU:1', device_type='XLA_GPU')]


In [43]:
# loading data
# load chapters mappings
BASE_PATH_DB = Path("/home/leo/projects/AI/Datasets/text/religion/bible/kaggle-bible-corpus")
KEY_PATH_DB = BASE_PATH_DB / "key_english.csv"

corpus_path = BASE_PATH_DB / "t_asv.csv"
with open(corpus_path, newline='') as f:
    corpus = csv.reader(f)
    corpus_db = [r for r in corpus]
    verses = [r[-1] for r in corpus_db[1:]]  # omit the first line; It's the header

In [45]:
verses[0]

'In the beginning God created the heavens and the earth.'

In [51]:
key_verse_map = {}

with open(KEY_PATH_DB, newline='') as f:
    rows = csv.reader(f)
    kvs = [r for r in rows]
    key_verse_map = { i[0] : i[1] for i in kvs[1:]}

In [52]:
key_verse_map

{'1': 'Genesis',
 '2': 'Exodus',
 '3': 'Leviticus',
 '4': 'Numbers',
 '5': 'Deuteronomy',
 '6': 'Joshua',
 '7': 'Judges',
 '8': 'Ruth',
 '9': '1 Samuel',
 '10': '2 Samuel',
 '11': '1 Kings',
 '12': '2 Kings',
 '13': '1 Chronicles',
 '14': '2 Chronicles',
 '15': 'Ezra',
 '16': 'Nehemiah',
 '17': 'Esther',
 '18': 'Job',
 '19': 'Psalms',
 '20': 'Proverbs',
 '21': 'Ecclesiastes',
 '22': 'Song of Solomon',
 '23': 'Isaiah',
 '24': 'Jeremiah',
 '25': 'Lamentations',
 '26': 'Ezekiel',
 '27': 'Daniel',
 '28': 'Hosea',
 '29': 'Joel',
 '30': 'Amos',
 '31': 'Obadiah',
 '32': 'Jonah',
 '33': 'Micah',
 '34': 'Nahum',
 '35': 'Habakkuk',
 '36': 'Zephaniah',
 '37': 'Haggai',
 '38': 'Zechariah',
 '39': 'Malachi',
 '40': 'Matthew',
 '41': 'Mark',
 '42': 'Luke',
 '43': 'John',
 '44': 'Acts',
 '45': 'Romans',
 '46': '1 Corinthians',
 '47': '2 Corinthians',
 '48': 'Galatians',
 '49': 'Ephesians',
 '50': 'Philippians',
 '51': 'Colossians',
 '52': '1 Thessalonians',
 '53': '2 Thessalonians',
 '54': '1 Timothy

In [40]:
# TF Universal Sentence Encoder models
#@title Load the Universal Sentence Encoder's TF Hub module
MODELS_BASE_PATH = "/home/leo/projects/AI/Datasets/Tensorflow/tf-hub/"
# module_url = os.path.join(BASE_PATH, "universal-sentence-encoder-lite_2")
module_url = os.path.join(MODELS_BASE_PATH, "universal-sentence-encoder-multilingual_3")
# module_url = "https://tfhub.dev/google/universal-sentence-encoder-multilingual/3"
# module_url = "https://tfhub.dev/google/universal-sentence-encoder-lite/2"
# module_url = "https://tfhub.dev/google/universal-sentence-encoder/4"
# module_url = 'https://tfhub.dev/google/universal-sentence-encoder-large/5'

In [10]:
model = hub.load(module_url)
print ("module %s loaded" % module_url)

def embed(input):
  return model(input)

module /home/leo/projects/AI/Datasets/Tensorflow/tf-hub/universal-sentence-encoder-multilingual_3 loaded


In [11]:
# I don't get wht this consumes so much CPU and memory and is even slower than the full cpu version
# %%time

# with tf.device('/GPU:1'):
#     model = hub.load(module_url)
#     print ("module %s loaded" % module_url)

#     def embed(input):
#       return model(input)

#     bible_embeddings = embed(verses)

In [12]:
%%time

bible_embeddings = embed(verses)

CPU times: user 2min 30s, sys: 33.6 s, total: 3min 4s
Wall time: 29.7 s


In [13]:
# bible_embeddings[0]

In [14]:
%%time
# similarity by inner product
similarity_matrix_inner = np.inner(bible_embeddings, bible_embeddings)

CPU times: user 11.2 s, sys: 738 ms, total: 12 s
Wall time: 3.09 s


In [15]:
similarity_matrix_inner.shape

(31103, 31103)

In [16]:
def check_symmetric(a, rtol=1e-05, atol=1e-08):
    return np.allclose(a, a.T, rtol=rtol, atol=atol)

the matrix must be symmetric

In [17]:
check_symmetric(similarity_matrix_inner)

True

In [18]:
# labels = 

In [19]:
# too big for my PC 
# sns.set(font_scale=1.2)
# g = sns.heatmap(
#   similarity_matrix_inner,
# #       xticklabels=labels,
# #       yticklabels=labels,
#   vmin=0,
#   vmax=1,
#   cmap="YlOrRd")
# g.set_xticklabels(labels, rotation=90)
# g.set_title("Semantic Textual Similarity")


In [20]:
%%time
# get the closest and farthest ~ N for each
# https://www.kite.com/python/answers/how-to-find-the-n-maximum-indices-of-a-numpy-array-in-python
# https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html
# https://numpy.org/doc/stable/reference/generated/numpy.partition.html

n = 21  # such as n>1 , when n==1 it shows only self-similarity
partitions = np.argpartition(similarity_matrix_inner, -n, axis=0)
closests = partitions[-n:]
farthest = partitions[:n]

CPU times: user 13.7 s, sys: 625 ms, total: 14.3 s
Wall time: 14.4 s


In [21]:
len(closests)
closests[0].shape

(31103,)

In [22]:
%%time
# now there are 2 arrays, each with verses number of elements, each array contains 
n_close = np.array(closests).transpose()
n_far = np.array(farthest).transpose()

CPU times: user 0 ns, sys: 3.56 ms, total: 3.56 ms
Wall time: 3.34 ms


In [23]:
similarity_matrix_inner.shape, n_close.shape, n_far.shape

((31103, 31103), (31103, 21), (31103, 21))

In [53]:
n_close[:2]

array([[15337, 31055, 26045, 19212, 24736, 16628, 13772, 26046, 15845,
        18579, 16474, 29973,   148,  5200, 28593,    31, 16625,    16,
           34, 15380,     0],
       [12522,  1910,   182,   190,    27, 14133, 19050,   194, 17829,
            8, 30527,  1928,   149,   176,   177, 25278,   178,     1,
           36,    37, 17530]])

In [24]:
# clean up memory ..
del(closests)
del(farthest)


Show the similarity values for a few points

In [25]:
similarity_matrix_inner[0][n_close[0][:20]]

array([0.5309429 , 0.53220767, 0.535607  , 0.54301083, 0.55235803,
       0.57052946, 0.55402035, 0.5800376 , 0.5822105 , 0.5618566 ,
       0.56626326, 0.57259107, 0.60005933, 0.5615088 , 0.5582243 ,
       0.6272632 , 0.65638304, 0.6330644 , 0.70625603, 0.64020944],
      dtype=float32)

In [26]:
similarity_matrix_inner[0][n_far[0]]

array([ 0.09364344,  0.08305697,  0.06654037,  0.12651277,  0.07592306,
        0.14878714,  0.13647093,  0.13357072,  0.05880683, -0.02358215,
        0.06586871,  0.11249685,  0.14682116,  0.0791003 ,  0.10768902,
        0.11913791,  0.13447869,  0.15217146,  0.11318401,  0.13786386,
        0.05275048], dtype=float32)

In [27]:
# n_close_distance = np.take_along_axis(similarity_matrix_inner, n_close, axis=0)  #this does not work

In [28]:
# n_close_distance = similarity_matrix_inner[tuple(n_close)]  # this does not work either
# n_close_distance = similarity_matrix_inner[n_close]  # this does not work either, it overloads the memory

In [29]:
# tnclose = tuple(n_close)  

In [30]:
# n_far_distance =  similarity_matrix_inner[n_far]  # Nope, this overloads the memory

extract similarity values for the close elements (this will be useful for displaying later the 

In [31]:
%%time
# somehow this is not sorted as it should
close_matrix = np.array([similarity_matrix_inner[i][n_close[i]] for i in range(similarity_matrix_inner.shape[0])])
far_matrix = np.array([similarity_matrix_inner[i][n_far[i]] for i in range(similarity_matrix_inner.shape[0])])

CPU times: user 73.4 ms, sys: 3.51 ms, total: 76.9 ms
Wall time: 77.2 ms


In [32]:
close_matrix.shape, far_matrix.shape

((31103, 21), (31103, 21))

In [33]:
close_matrix[0]

array([0.5309429 , 0.53220767, 0.535607  , 0.54301083, 0.55235803,
       0.57052946, 0.55402035, 0.5800376 , 0.5822105 , 0.5618566 ,
       0.56626326, 0.57259107, 0.60005933, 0.5615088 , 0.5582243 ,
       0.6272632 , 0.65638304, 0.6330644 , 0.70625603, 0.64020944,
       1.0000001 ], dtype=float32)

In [34]:
# now I need to understand many MANY things, 
# compute the labels and IDs for each row
# give the text for each row
# create a networkx connection graph with it


Compute Human Readable Labels

In [55]:
corpus_db[0]

['id', 'b', 'c', 'v', 't']

In [39]:
corpus_db[11000:11003]

[['13023016', '13', '23', '16', 'The sons of Gershom: Shebuel the chief.'],
 ['13023017',
  '13',
  '23',
  '17',
  'And the sons of Eliezer were: Rehabiah the chief; and Eliezer had no other sons; but the sons of Rehabiah were very many.'],
 ['13023018', '13', '23', '18', 'The sons of Izhar: Shelomith the chief.']]

In [331]:
%%time
# db contains all the information AND the embeddings, this also contains the graph information
bible_db = {}

for i in range(1, len(corpus_db)-1):
    verse = corpus_db[i]
#     k_id = int(verse[0])
    val = {
        'index':i-1,
        'id': int(verse[0]),
        'name': f"{key_verse_map[verse[1]]} {verse[2]}:{verse[3]}",
        'book_id': int(verse[1]),
        'chapter_id': int(verse[2]),
        'verse_id': int(verse[3]),
        'text': verse[4],
        'embedding': bible_embeddings[i],
        'close_to': n_close[i],  # ids
        'close_to_distance': close_matrix[i], 
        'far_from': n_far[i],  # ids
        'far_from_distance': far_matrix[i], 
    }
    bible_db[i-1] = val

CPU times: user 1.58 s, sys: 9.67 ms, total: 1.59 s
Wall time: 1.6 s


In [332]:
bible_db[10]

{'index': 10,
 'id': 1001011,
 'name': 'Genesis 1:11',
 'book_id': 1,
 'chapter_id': 1,
 'verse_id': 11,
 'text': "And God said, Let the earth put forth grass, herbs yielding seed, `and' fruit-trees bearing fruit after their kind, wherein is the seed thereof, upon the earth: and it was so.",
 'embedding': <tf.Tensor: shape=(512,), dtype=float32, numpy=
 array([ 0.09106142,  0.03639635,  0.07232352,  0.0180516 ,  0.00536718,
         0.03608396,  0.05259072, -0.02857068,  0.04545586,  0.06467625,
         0.06814095, -0.03513066,  0.02862555,  0.02917071, -0.00231802,
         0.00881511, -0.05753801,  0.04993311, -0.01497626,  0.01349286,
         0.01813623, -0.02739129,  0.03048592, -0.03268808, -0.07027489,
         0.06431985, -0.05512333, -0.06109827, -0.0350656 ,  0.0462325 ,
        -0.05182962, -0.06845409, -0.0513493 ,  0.02085048,  0.00632241,
         0.00783822,  0.04397808, -0.00993006, -0.05865693,  0.02339393,
         0.00523461, -0.06789356, -0.07403339, -0.0083824 , -

In [333]:
# save the DB
BIBLE_DB_PATH = "../db/bible-db.pkl"
with open(BIBLE_DB_PATH, 'wb') as f:
    pickle.dump(bible_db, f, pickle.HIGHEST_PROTOCOL)
    
## kind of big, 86 mb

In [334]:
BIBLE_EMBEDDINGS_PATH = "../db/bible-embeddings.pkl"
with open(BIBLE_EMBEDDINGS_PATH, 'wb') as f:
    pickle.dump(bible_embeddings, f, pickle.HIGHEST_PROTOCOL)
    

In [296]:
# # function to get the subgraph 

# def _get_node_edge(bible_db, node_id, close_points):
#     node = bible_db[node_id]
# #     group = node['book_id']
# #     label = node['name']
# #     title = node['text']
# #     txt = node['text']
#     nd_info = (node_id, node)
#     nd_weight = zip(node['close_to'], node['close_to_distance'])
#     nd_edges = []
#     for n,w in nd_weight:
#         if n != node_id:
#             # distance is farthest the smaller it is, so changing it to make the reverse relation
#             nd_edges.append((node_id, n, 1/w))
#         if len(nd_edges) >= close_points:
#             break
#     return nd_info, nd_edges

In [297]:
# def get_subgraph(bible_db, node_id, close_points=5, levels=2):
#     """
#     Get the subgraph from a node id
#     bible_db: the entire bible database in a dict
#     node_id: the node id
#     close_points: the number of close points from each, => each point will have at most close_points outgoing edges
#     levels: number of levels to go in depth for connections
#     returns a networkx graph of the subgraph from the complete db centering the subgraph in the given node_id
#     """
#     g = nx.Graph()
#     if node_id not in bible_db:
#         # there is no graph to build
#         return g
#     # Recursive is SO intuitive, but will explode the stack and memory for big graphs
#     nid = node_id
#     nodes_to_add = []  # (node_id, group, size, label, title, txt)
#     edges_to_add = []  # (node_id, node_id, weight)
#     discovered = set()
#     q = Queue()
#     q.put((node_id, 0))  # keep (node, depth from center in levels)
#     cnt = 0
#     # this tree/ graph transversal is wrong, but I need to be able to build something first
#     # this is still wrong as it will explore all the first subset from the first last level, but for the moment kind of works
#     while not q.empty() and cnt < levels+1:
#         v, lvl = q.get()
#         discovered.add(v)
#         nd_info, nd_edges = _get_node_edge(bible_db, v, close_points)
#         nodes_to_add.append((nd_info, lvl))
#         edges_to_add.append((nd_edges, lvl))
#         for te,ne,w in nd_edges:
#             if ne not in discovered:
#                 q.put((ne, lvl+1))
#         cnt = lvl
#     # TODO
#     for n, lvl in nodes_to_add:
#         if lvl < levels:
#             nid, node = n
# #             g.add_node(nid)
#             g.add_node(nid, size=20, group=node['book_id'], title=node['name'], data=node['text'])
# #         g.add_node(int(nid), size=20, group=node['book_id'], title=node['name'], data=node['text'])
    
#     for edges, lvl in edges_to_add:
#         if lvl >= levels:
#             break
#         for (se, ee, w) in edges:
# #             g.add_edge(se, ee, weight=w)
#             g.add_edge(se, ee)

#     return nodes_to_add, edges_to_add, g

In [410]:
# function to get the subgraph 

def _get_edges(n_index, node, close_points):
    """
    n_index: node index in the encoding matrix
    node: the node in the db
    close_points: the number of close points to get
    """
    nd_weight = zip(node['close_to'], node['close_to_distance'])
    nd_edges = []
    for n,w in nd_weight:
        if n != n_index:
            # distance is farthest the smaller it is, so changing it to make the reverse relation
            nd_edges.append((n_index, n, 1/w))
        if len(nd_edges) >= close_points:
            break
    return nd_edges


def get_subgraph(bible_db, node_id, close_points=5, levels=2):
    """
    Get the subgraph from a node id
    bible_db: the entire bible database in a dict
    node_id: the node id
    close_points: the number of close points from each, => each point will have at most close_points outgoing edges
    levels: number of levels to go in depth for connections
    returns a networkx graph of the subgraph from the complete db centering the subgraph in the given node_id
    """
    g = nx.Graph()
    if node_id not in bible_db:
        # there is no graph to build
        return g
    # Recursive is SO intuitive, but will explode the stack and memory for big graphs
    nid = node_id
    nodes_to_add = []  # (node_id, group, size, label, title, txt)
    edges_to_add = []  # (node_id, node_id, weight)
    discovered = set()
    q = Queue()
    q.put((node_id, 0))  # keep (node, depth from center in levels)
    cnt = 0
    # this tree/ graph transversal is not WOW HOW EFFICIENT, but it works well enough
    while not q.empty() and cnt < levels+1:
        node_id, lvl = q.get()
        discovered.add(node_id)
        node = bible_db[node_id]
        nodes_to_add.append((node, lvl))
        # only add the edges if the level is not the max
        if lvl < levels:
            nd_edges = _get_edges(node_id, node, close_points)
            for edg in nd_edges:
                edges_to_add.append((edg, lvl))
                sn, en, w = edg
                if en not in discovered:
                    q.put((en, lvl+1))
        cnt = lvl
    # TODO
    for node, lvl in nodes_to_add:
#         if lvl < levels:
# #             g.add_node(nid)
        g.add_node(node['index'], size=20, group=node['book_id'], title=node['name'], data=node['text'])
#         g.add_node(int(nid), size=20, group=node['book_id'], title=node['name'], data=node['text'])
    
    for edg, lvl in edges_to_add:
        (sn, en, w) = edg
#         print(edg)
        # pyvis complains that this are not int fields!! (but they are)
        g.add_edge(int(sn), int(en), weight=w)
#         g.add_edge(sn, en)

    return nodes_to_add, edges_to_add, g

In [423]:
nodes, edges, sg = get_subgraph(bible_db, 127, close_points=10, levels=3)

In [424]:
[(n[0]['index'], n[1]) for n in nodes]

[(127, 0),
 (124, 1),
 (3688, 1),
 (3627, 1),
 (120, 1),
 (3778, 1),
 (123, 1),
 (282, 1),
 (137, 1),
 (233, 1),
 (288, 1),
 (131, 2),
 (291, 2),
 (130, 2),
 (133, 2),
 (116, 2),
 (114, 2),
 (132, 2),
 (136, 2),
 (113, 2),
 (119, 2),
 (3682, 2),
 (3669, 2),
 (4523, 2),
 (4716, 2),
 (3673, 2),
 (3631, 2),
 (3643, 2),
 (3629, 2),
 (3674, 2),
 (3714, 2),
 (3781, 2),
 (3640, 2),
 (3638, 2),
 (3622, 2),
 (3624, 2),
 (3626, 2),
 (3636, 2),
 (3634, 2),
 (3606, 2),
 (3628, 2),
 (130, 2),
 (281, 2),
 (6878, 2),
 (280, 2),
 (123, 2),
 (117, 2),
 (291, 2),
 (289, 2),
 (115, 2),
 (287, 2),
 (12030, 2),
 (3677, 2),
 (2662, 2),
 (11744, 2),
 (4530, 2),
 (3625, 2),
 (3714, 2),
 (4507, 2),
 (3629, 2),
 (3662, 2),
 (292, 2),
 (277, 2),
 (125, 2),
 (133, 2),
 (285, 2),
 (117, 2),
 (126, 2),
 (130, 2),
 (112, 2),
 (9522, 2),
 (726, 2),
 (13938, 2),
 (280, 2),
 (4799, 2),
 (278, 2),
 (277, 2),
 (283, 2),
 (289, 2),
 (5495, 2),
 (19589, 2),
 (1287, 2),
 (7125, 2),
 (6919, 2),
 (25995, 2),
 (138, 2),
 (1323

In [425]:
edges

[((127, 124, 1.9206106677977026), 0),
 ((127, 3688, 1.9199284450496363), 0),
 ((127, 3627, 1.916513204031377), 0),
 ((127, 120, 1.9039842317590059), 0),
 ((127, 3778, 1.8744770173663696), 0),
 ((127, 123, 1.6678171013618526), 0),
 ((127, 282, 1.7926436842525915), 0),
 ((127, 137, 1.85475294637371), 0),
 ((127, 233, 1.664899873097303), 0),
 ((127, 288, 1.667878448548049), 0),
 ((124, 131, 2.034440868828576), 1),
 ((124, 291, 2.016696401246376), 1),
 ((124, 130, 2.0010460122542066), 1),
 ((124, 133, 1.8872998292148948), 1),
 ((124, 116, 1.651623309118631), 1),
 ((124, 114, 1.838141341684569), 1),
 ((124, 132, 1.4620073816610148), 1),
 ((124, 136, 1.716840848845453), 1),
 ((124, 113, 1.5149321427133127), 1),
 ((124, 119, 1.5527609858021887), 1),
 ((3688, 3682, 1.5681176997522748), 1),
 ((3688, 3669, 1.563569459073628), 1),
 ((3688, 4523, 1.5572207443599393), 1),
 ((3688, 4716, 1.5561025387601537), 1),
 ((3688, 3673, 1.5176644569134303), 1),
 ((3688, 3631, 1.5032326657382948), 1),
 ((3688,

In [426]:
type(sg)

networkx.classes.graph.Graph

In [427]:
sg.nodes[127]

{'size': 20,
 'group': 1,
 'title': 'Genesis 5:22',
 'data': 'and Enoch walked with God after he begat Methuselah three hundred years, and begat sons and daughters:'}

In [430]:
# sg.nodes

In [431]:
# sg.edges

In [435]:
# options = {
#     'node_color': 'yellow',
#     'node_size': 600,
# #     'width': 3,
# #     'arrowstyle': '-|>',
# #     'arrowsize': 12,
# }
# nx.draw_networkx(sg, **options)
# plt.show()

In [436]:
# gg = nx.from_edgelist(list(sg.edges))

In [437]:
# options = {
#     'node_color': 'pink',
#     'node_size': 600,
# #     'width': 3,
# #     'arrowstyle': '-|>',
# #     'arrowsize': 12,
# }
# nx.draw_networkx(gg, **options)
# plt.show()

In [438]:
nt = Network('800px', '800px', notebook=True)
nt.from_nx(sg)

In [439]:
nt.show('nx.html')

In [367]:
def get_closest_points(txt, n=10, algorithm='inner'):
    """
    txt: the text to look for similarities
    n: the number of closest matches that will be searched
    algorithm: inner|cosine  # the algorithm to determine how the proximity is computed
    returns the closest n points to the input text based on the proximity algorithm
    """
    n_close = []
    # TODO
    # embed input
    # compute proximity with all the existing points
    # get the closest n points ids
    return n_close


In [368]:
nx_graph = nx.Graph()
# nx_graph = nx.cycle_graph(10)
# nx_graph.nodes[1]['title'] = 'Number 1'
# nx_graph.nodes[1]['group'] = 1
# nx_graph.nodes[3]['title'] = 'I belong to a different group!'
# nx_graph.nodes[3]['group'] = 10
nx_graph.add_node(20, size=20, title='couple', group=2)
nx_graph.add_node(21, size=15, title='couple', group=2)
nx_graph.add_edge(20, 21, weight=5)
nx_graph.add_node(25, size=25, label='lonely', title='lonely node', group=3)
nt = Network('500px', '500px', notebook=True)

In [369]:
for node, lvl in nodes:
    nx_graph.add_node(node['index'], size=20, group=node['book_id'], title=node['name'], data=node['text'])

In [370]:
# populates the nodes and edges data structures
nt.from_nx(nx_graph)
nt.show('nx.html')